version: '3'
services:

  # Creates an InfluxDB
  influxdb:
    image: influxdb:1.8
    restart: always
    volumes:
      - /media/docker/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=iobroker

  # Creates a Grafana dashborad
  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - /media/docker/grafana:/var/lib/grafana
