#!/bin/bash

echo " "
echo "System Update"
echo "-------------"
sleep  1
sudo apt update
sudo apt dist-upgrade
sudo apt install curl -y

echo " "
echo "Install IoBroker"
echo "----------------"
sleep 1
curl -sLf https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install nodejs -y
curl -sLf https://iobroker.net/install.sh | bash -

echo " "
echo "Install Docker"
echo "--------------"
sleep 1
curl -sSL https://get.docker.com | sh

echo " "
echo "Install Docker-Compose"
echo "----------------------"
sleep 1
sudo apt install libffi-dev libssl-dev -y
sudo apt install python3-dev -y
sudo apt install python3 python3-pip -y
sudo pip3 install docker-compose

echo " "
echo "Create Folders"
echo "--------------"
sleep 1
sudo mkdir /media/docker
sudo mkdir /media/docker/iobingraf
sudo mkdir /media/docker/influxdb
sudo mkdir /media/docker/grafana
sudo chmod 775 /media/docker/influxdb
sudo chmod 775 /media/docker/grafana

echo " "
echo "Create InfluxDB and Grafana Container"
echo "-------------------------------------"
sleep 1
wget https://github.com/rathio-git/iobingraf/blob/main/docker-compose.yaml
sudo mv docker-compose.yaml /media/docker/iobingraf/docker-compose.yaml
sudo docker-compose /media/docker/iobingraf/docker-compose.yaml

echo " "
echo "InfluxDB data"
echo "user=admin"
echo "password=admin"
echo "DB-Name=iobroker"
echo " "


