#!/usr/bin/env sh

echo ""
echo ""
echo "Influxdb database for IoBroker"
echo "-----------------------------"
echo ""
tput setaf 2; echo "Please enter a name for the database"
tput sgr0; read dbname 

echo ""
tput setaf 2; echo "Please enter a name for the admin-user of the Iobroker database"
tput sgr0; read adminname

echo ""
tput setaf 2; echo "Please enter a password for the admin-user"
tput sgr0; read  adminpassword


echo " "
echo " "
echo "System Update"
echo "-------------"
sleep  1
sudo apt update
sudo apt dist-upgrade
sudo apt install curl -y

echo " "
echo "Install IoBroker"
echo "----------------"
sleep 1
curl -sLf https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install nodejs -y
curl -sLf https://iobroker.net/install.sh | bash -

echo " "
echo "Install Docker"
echo "--------------"
sleep 1
curl -sSL https://get.docker.com | sh

echo " "
echo "Install Docker-Compose"
echo "----------------------"
sleep 1
sudo apt install libffi-dev libssl-dev -y
sudo apt install python3-dev -y
sudo apt install python3 python3-pip -y
sudo pip3 install docker-compose

echo " "
echo "Create Folders"
echo "--------------"
sleep 1
sudo mkdir /media/docker
sudo mkdir /media/docker/iobingraf
sudo mkdir /media/docker/influxdb
sudo mkdir /media/docker/grafana
sudo chmod 775 /media/docker/influxdb
sudo chmod 775 /media/docker/grafana

echo " "
echo "Create InfluxDB and Grafana Container"
echo "-------------------------------------"
sleep 1
echo "db_name="$dbname >> .envtmp
echo "db_user="$adminname >> .envtmp
echo "user_pw="$adminpassword >> .envtmp
wget https://raw.githubusercontent.com/rathio-git/iobingraf/main/docker-compose.yaml
sudo mv docker-compose.yaml /media/docker/iobingraf/docker-compose.yaml
sudo mv .envtmp /media/docker/iobingraf/.env
cd /media/docker/iobingraf
sudo docker-compose up -d
cd ~
clear
echo " "
echo " "
echo "Installation complete"
echo "---------------------"
echo " "
echo "Iobroker"
echo "Port = 8081"
echo " "
echo "----------------"
echo " "
echo "InfluxDB"
echo "Port = 8086"
echo "DB-Name = "$dbname
echo "User = "$adminname
echo "Password = "$adminpassword
echo " "
echo "----------------"
echo " "
echo "Grafana"
echo "Port = 3000"
echo " "
echo " "
echo "Have a lot of fun." 
echo "rathio"
echo " "
echo " "


